# Generated by Django 3.0.4 on 2020-03-27 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandname',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='bandname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bandname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='bandname_text',
            field=models.CharField(max_length=255, verbose_name='Band Name'),
        ),
    ]
