# Generated by Django 4.2.6 on 2023-10-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='openai_prompt',
            field=models.TextField(default='', verbose_name='OpenAI Prompt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bandname',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bandname',
            name='openai_prompt',
            field=models.TextField(default='', verbose_name='OpenAI Prompt'),
            preserve_default=False,
        ),
    ]
