# Generated by Django 4.2.6 on 2023-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0003_album_image_album_openai_prompt_bandname_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='openai_prompt',
            field=models.TextField(null=True, verbose_name='OpenAI Prompt'),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='openai_prompt',
            field=models.TextField(null=True, verbose_name='OpenAI Prompt'),
        ),
    ]
